### ISSUE TITLE
Right click resets the zoom to RuneLite default when opening/closing sidepanel in resizable mode

### ISSUE THREAD

**Issue by keywok** [YvesW/default-minimap-zoom#2]
Even with the option ticked when you right click on the minimap it zooms it all the way back in. If you toggle the plugin it works for one or two clicks then goes back to having right click reset the zoom.

[GIF demonstration](https://imgur.com/5Ua8FP5)

**Comment by YvesW** [comment]
After some testing via Discord, most likely cause by opening/closing sidepanel while in resizable mode.

Fixed in 5251bfc3c21f96c7888066f98ef9e6d33e5bcc7f
